---
title: "william"
output: html_document
---

----
title
---

```{r}
variable.1 = c(3,4,5,6) 
variable.2 <- c("Hello"," there") 
c(TRUE,2) -> variable.3

print(variable.1) 
print(variable.2)
print(variable.3)
```

```{r}
m = 62.4 # assign a decimal value to m 
m # prints the variable's value m
```
----
Integer Data Type
Any integer in R is created by invoking the as.integer() function as shown below:
-----
```{r}
n = as.integer(3) 
n # prints the value of n
```

```{r}
p = as.integer(3.14) 
p # prints in a numeric value
```
```{r}
k = 1 + 2i # creating a complex number 
k # prints the complex number
```

```{r}
x = 4; y = 6 # sample values 
z = x > y # is x larger than y? 
z # prints the logical value
```

exercise 1

```{r}
## Example
# ----
# Let's first assign the variable x the value 5 and also assign the variable y the value 16. 
# ---
# 
x <- 5 
y <- 16 

## Then, we add x and y together using the addition operator +
# ---
#
x + y

```

```{r}
## Challenge 
# ---
# Question: Fix the code below to get an output of 1. 
# Hint: You can change the values of the variables to get the output.
# ---
# OUR CODE GOES BELOW
# 

c <- 11
d <- 2
c %% d
```
```{r}
## Example 
# ---
# Question: Let create two vectors v and t
# ---
# 
v <- c(3,1,TRUE,2+3i) 
t <- c(4,1,FALSE,2+3i) 

# This time, use the logical not operator ||
v||t
```
```{r}
v1 <- c(3,1,TRUE,2+3i) 
v2 <<- c(3,1,TRUE,2+3i) 
v3 = c(3,1,TRUE,2+3i) 
print(v1)
print(v2)
print(v3)
```

```{r}
c(3,1,TRUE,2+3i) -> v1 
c(3,1,TRUE,2+3i) ->> v2 
print(v1)
print(v2)

```

```{r}
g=as.character(6.3)
```

List
# Lists are R objects which contain elements of different types 
# like numbers, strings, vectors, matrices, functions and lists too.
# ---
# Question: Create a list using the list() function
# ---

# OUR CODE GOES BELOW
# ---
#
```{r}
alist <- list ("Red", "Blue", c(42,36,01), FALSE, 73.91, 128.6)
alist
```

```{r}
## Example 
# ---
# Question: Create vectors a, b and c 
# ---
# 
a <- c(1,2,5.3,6,-2,4)                   # numeric vector 
b <- c("one","two","three")              # character vector 
c <- c(TRUE,TRUE,TRUE,FALSE,TRUE,FALSE)  # logical vector

print(a)
print(b)
print(c)
```

```{r}
list_data <- list(c("Jan","Feb","Mar"), matrix(c(3,9,5,1,-2,8), nrow = 2))
list_data[4]<-"new element"
list_data
```
```{r}


